import Navbar from './components/navbar/Navbar';
import './globals.css'
import { Nunito } from "next/font/google";

export const metadata = {
  title: 'MERIT',
  description: 'Generated by MERIT',
}

const font = Nunito({
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-light-beige`}>
        <Navbar />
        
        {children}</body>
    </html>
  )
}
